### ISSUE TITLE
asp.net web pages requirements

### ISSUE THREAD

**Issue by villanus** [reactjs/React.NET#100]
what are the requirements of running with web pages and not mvc?

**Comment by Daniel15** [comment]
That's a good question, I've never used Web Pages before. I know it uses
Razor but does it use the same HtmlHelpers as MVC? Try installing the
ReactJS.NET MVC package and seeing if that works.

**Comment by Daniel15** [comment]
Closing this since I haven't heard back, but let me know if the MVC helpers don't work with Web Pages and I can investigate. I can't actually figure out how to create a Web Pages site in the Visual Studio 2015 preview so I may need to downgrade to Visual Studio 2013 to test this out (or use WebMatrix).

**Comment by villanus** [comment]
Thanks for investigating.  I never had the time to get into react =(
