### ISSUE TITLE
TransformJsx task failing unexpectedly.

### ISSUE THREAD

**Issue by Semblant** [reactjs/React.NET#104]
Hi all,

I'm getting a handful of errors when attempting to build a Web API project (ASP.NET 4).
![image](https://cloud.githubusercontent.com/assets/4534713/6630748/9e3f7eb6-c8d9-11e4-8240-7c02db003f90.png)

I am using the default TransformJsx.proj:
![image](https://cloud.githubusercontent.com/assets/4534713/6630799/3761bb04-c8da-11e4-824b-548bddece69a.png)

I have attempted adding a TargetDir property as seen here(http://reactjs.net/guides/msbuild.html) but had no luck.

Any help would be greatly appreciated.

**Comment by Daniel15** [comment]
I recently saw the same thing on my own site after upgrading Newtonsoft.Json (JSON.NET) past version 5.0.4. Downgrading to JSON.NET version 5.0.4 made it work as expected so there's probably some incompatibility somewhere. I'll take a look.

**Comment by Semblant** [comment]
Hey Daniel, thanks for the suggestion. Unfortunately, JSON.NET 5.0.4 is incompatible with Microsoft.Owin.Security (version 3.0.0) and others.

I also tried upgrading from JSON.NET 6.0.4 to 6.0.8 because it looked like there were some 'unsupported type' fixes. No luck there either. If it weren't for the security requirements of this project, I would just downgrade to 5.0.4.

Thanks for your attention on the issue, I will check back.

**Comment by Daniel15** [comment]
I'll try to take a look this weekend and see if I can figure out what's up :)

**Comment by Daniel15** [comment]
That was pretty tricky to track down, but it did end up being an issue with the JSON.NET version:

![Error message](https://cloud.githubusercontent.com/assets/91933/6659698/511cc3d4-cb48-11e4-8d47-a3dc3c680a4a.PNG)

The "real" error message was masked by that try-catch block in that segment of code. The `try` block had logic for parsing the data as JSON, but the `catch` block did not. This meant that the error that ended up being thrown was due to the code paths being different, which is why I was confused by it.

This actually seems somewhat specific to the MSBuild task which is probably why I haven't gotten other reports about it (not many people use the MSBuild task). NuGet automatically inserts assembly bindings into the Web.config which means assembly version issues don't really happen with sites (or desktop apps). MSBuild can't really use assembly bindings.

Anyways, 5021d39e5c1cba600863332e7e2dc043b2321750 fixed the code so the two code paths do the same thing (which made it start throwing the correct error about Newtonsoft.Json) and 292cf49bd08b6da775838eb1b14eb6a769402897 updated the referenced version of Newtonsoft.Json. The new build will be on the development package server shortly ([instructions here](http://reactjs.net/getting-started/download.html#development-builds)), or you can build it yourself if you like.

**Comment by Semblant** [comment]
Awesome Daniel, thanks for the support. I will give it a whirl in the
morning.

**Comment by Semblant** [comment]
I gave the development package a whirl but bumped into the same issue (the update might not have propagated yet?). I did build it and my issue has been resolved, thanks again.

**Comment by Daniel15** [comment]
Yeah it looks like the build on the dev server is broken even though I have
no issues compiling the project myself (even on a fresh checkout), not
quite sure what's going on there. Thanks for checking it :)

--
Regards,
Daniel Lo Nigro
http://dan.cx/ | Twitter <http://twitter.com/Daniel15> | Facebook
<http://www.facebook.com/daaniel>
