### ISSUE TITLE
How can we avoid ReactDOMServer being sent to the client making the bundles too big?

### ISSUE THREAD

**Issue by johot** [reactjs/React.NET#1080]
Thanks again for this great project!

In the webpack sample here: https://reactjs.net/bundling/webpack.html

It seems that ReactDOMServer gets bundled which ofc is needed for the SSR rendering. But doesn't this also mean that it will be sent to the client when doing Html.ReactInitJavascript?

Does ReactJS.NET do anything special to avoid this or would you need support for a separate server and client bundle so the client bundle can drop the ReactDOMServer code?

Thank you again!

**Comment by dustinsoftware** [comment]
Hey you’re welcome!

You’ll need to create a separate client bundle if you want to strip that
out. It’s pretty small so for now though so we recommend keeping a single
bundle configuration. Otherwise you’ll need to add extra handling on your
app to reference the client bundle only on the client (which maybe is
worthwhile for us to include in the docs if we can provide straightforward
helpers to do that....)

**Comment by johot** [comment]
Ok thank you @dustinsoftware that answers my questions!
