### ISSUE TITLE
It is possible to have separate ReactSiteConfigurations for each MVC area?

### ISSUE THREAD

**Issue by ipoley-r7** [reactjs/React.NET#1100]
We're currently using MVC areas in our project and would love to have separate `ReactSiteConfigurations` per site. Currently, even if you put the `ReactSiteConfiguration` within the `AreaRegistration`, the configuration gets shared between all configured areas. 

Is there any easy fix for being able to separate the `ReactSiteConfigurations` on a per-area basis?

**Comment by dustinsoftware** [comment]
Most likely no. This library makes heavy use of static properties to access
the current React configuration and JS instance. It probably could be
reworked to use the .NET Core service injection system but I don’t know if
that is area specific.

I recommend separate Web projects instead of using Areas, with common logic
in a shared helper class library.
