### ISSUE TITLE
Tutorial change to fix IE caching of comment ajax response

### ISSUE THREAD

**Issue by andersea** [reactjs/React.NET#111]
IE will aggressively cache ajax responses. In the tutorial the list of comments is retrieved from the server using the following method.

```csharp
public ActionResult Comments()
{
	return Json(_comments, JsonRequestBehavior.AllowGet);
}
```
This will not work out of the box in IE because the response is cached and will not contain the newly added comment.

To prevent IE from caching the response, you can add a Cache-Control header to the response like this:

```csharp
public ActionResult Comments()
{
	Response.Cache.SetCacheability(HttpCacheability.NoCache);

	return Json(_comments, JsonRequestBehavior.AllowGet);
}
```

**Comment by Daniel15** [comment]
Good catch!

With ASP.NET MVC you'd ideally use the `OutputCache` attribute rather than calling `Response.Cache` directly. I think it's something like this:
```csharp
[OutputCache(Location = OutputCacheLocation.None)]
public ActionResult Comments()
``` 

Although disabling caching would result in reduced performance. In a production environment you'd ideally use proper cache validation (ie. E-Tags and Last-Modified/If-Modified-Since).

Feel free to send a pull request to update the tutorial, otherwise I can update it when I get some free time.
