### ISSUE TITLE
Error on run time when using React Intl

### ISSUE THREAD

**Issue by coyaniv** [reactjs/React.NET#126]
Hi, 
I'm having problem using React Intl. (http://intljs.io/react/)
I'm getting error only after publish my code to Azure env. In my local env everything works fine.
I'm getting this error:
"React.Exceptions.ReactScriptLoadException: Error while loading "~/dist/scripts/react-server.jsx": 'Intl' is undefined"

Thank you

**Comment by coyaniv** [comment]
Why this error display only on the Azure env.? What's the difference between Azure env to Local?

**Comment by Daniel15** [comment]
Are you using Webpack/Browserify, or are you listing all the required files in ReactConfig.cs? Could you please provide a small project that replicates the issue, so I can take a look?

**Comment by coyaniv** [comment]
https://drive.google.com/file/d/0B2eZcvKLnZ6lb0FDYWNYQ1Q2cnM/view?usp=sharing

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.

**Comment by magnusottosson** [comment]
Did you ever solve this? I guess that packages (such as react-intl) will never work with reactjs.net since Intl is not a part of ClearScript (https://github.com/microsoft/ClearScript/issues/150). Node has added support for Intl and one could just hope that ClearScript will add it as well.

I can be solved using the, no longer maintained, intl.js (https://github.com/andyearnshaw/Intl.js#readme) package but its not an ideal solution...

Anyone that has solved this in another way?
