### ISSUE TITLE
Use Babel to transform JS

### ISSUE THREAD

**Issue by zpao** [reactjs/React.NET#138]
We're likely going to stop supporting JSXTransformer soon. Babel has something similar so it should be relatively easy to swap in, with the upside that more ES* features are supported and they are implemented and fixed faster.

**Comment by Daniel15** [comment]
I suppose this means I should close #131 and instead look at how difficult it'd be to support Babel.

**Comment by zpao** [comment]
Probably. You're welcome to use newer JSXTransformer (or even just browserify latest JSTransform, which includes JSX, directly), we just won't support it officially.

**Comment by locksmithdon** [comment]
+1 Babel integration would be excellent. It has good JSX support and heaps of ES6 features.

**Comment by Daniel15** [comment]
@locksmithdon You can use Babel with ReactJS.NET today via Webpack (see the documentation at http://reactjs.net/guides/webpack.html). This update would just be for when you hit .jsx files in your browser directly, or use a .NET minification library (like Cassette or Microsoft's one)

**Comment by jslatts** [comment]
FWIW, we have been using Babel with ReactJS.NET and precompiling via Browserify + Babelify and gulp for quite awhile. We did it primarily for the ES6 transforms. Works great! I could write up a quick guide if there was interest.

**Comment by Daniel15** [comment]
There's some docs on Webpack (http://reactjs.net/guides/webpack.html) which I'm going to update to use Babel rather than JSXTransformer, but I'd be happy to add some docs for Browserify too.

The docs are in the same repo, the source for the Webpack one is here: https://github.com/reactjs/React.NET/blob/master/site/jekyll/guides/webpack.md

**Comment by Daniel15** [comment]
@jslatts - There's some docs on Webpack (http://reactjs.net/guides/webpack.html) which I'm going to update to use Babel rather than JSXTransformer, but I'd be happy to add some docs for Browserify too.

The docs are in the same repo, the source for the Webpack one is here: https://github.com/reactjs/React.NET/blob/master/site/jekyll/guides/webpack.md

**Comment by Daniel15** [comment]
Mostly done in dd752222d02b6ebd0dcdf69619a23d312d0b7f65. There's still a few things I'd like to do (eg. allow configuration of Babel options) but the basic stuff is there.
