### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by locksmithdon** [reactjs/React.NET#140]
I'm trying to use [Material-UI](http://material-ui.com) and I'm getting is error on the server-side. I've added the component I'm using ([TextField](http://material-ui.com/#/components/text-fields)) to `ReactConfig.cs` and I'm pretty sure this is what is causing the error. Is there a way to get React.NET to recognize `require()`? I have not disabled ES6 support because I'd like to use it, although Material-UI is obviously not. This is the first time I'm trying to use React.NET (still a n00b). Much thanks.

**Comment by Daniel15** [comment]
You'll have to use a module loader like Webpack or Browserify if you want
to use CommonJS modules, since there's no native .NET libraries that
support them. There's some documentation on using Webpack on the
ReactJS.NET site, and lots of general tutorials online.

Alternatively, get a non-module version of the code (often there's a
download available "for use in browsers" for that).

**Comment by locksmithdon** [comment]
Thanks for the ultra-rapid response @Daniel15. My buddy @kevnz said the same thing and pointed me to the resources you mentioned: http://reactjs.net/guides/webpack.html and https://github.com/reactjs/React.NET/tree/master/src/React.Sample.Webpack. These should prove to be very useful.
