### ISSUE TITLE
Is this ready for production?

### ISSUE THREAD

**Issue by andersekdahl** [reactjs/React.NET#143]
Hi!
This project looks really nice, and it's nice to see that it's backed by Facebook. That said, how production ready is this project? What kind of performance can you expect from the server rendering compared to Razor?

Any examples of sites that use it? Is it used internally at Facebook?

**Comment by Daniel15** [comment]
It's not used internally at Facebook, it was mainly a side project for me. I have one page on my site powered by it (http://dan.cx/socialfeed.htm). I know there's a few other people that use it in production but I can't remember the sites at the moment.

Server-side rendering performance should be pretty good if you use the JS engine pooling (which is enabled by default).

**Comment by andersekdahl** [comment]
Thanks for answering, much appreciated!

Have you done any benchmarks on the difference between rendering the same type of content with Razor and React? 

In your own view, would you be comfortable using this for a business critical site with moderate to heavy load?

**Comment by andersekdahl** [comment]
Btw, didn't mean to throw you a curve ball question about your project like that. I have every intention to research this myself as well (and of course share my findings!).

**Comment by andersekdahl** [comment]
Here are the results of some early tests. The tests are a bit naive, so take the results for what they are.

I created three projects, one with vanilla MVC and a few Razor views. The second project outputs the exact same thing, but with React.NET instead of Razor. And the third also outputs the same but using React with Node.js.

The test was to send 100 000 requests through Apache Bench to them on my Windows 8 developer machine.

Razor won the tests. Node.js came in at about 50% slower than that, and React.NET at about 800% slower than Razor.

800% might sound like a lot but I'm quite impressed given how little the Razor-project had to do in comparison.

**Comment by Daniel15** [comment]
> The test was to send 100 000 requests through Apache Bench to them on my Windows 8 developer machine.

It'd be great if you could upload your benchmarking code. ReactJS.NET hasn't been heavily optimised yet so potentially there's some slow code paths that could be improved

Did you have JavaScript engine pooling enabled? It's on by default. How many concurrent requests were you doing? By default there's an upper limit of 25 concurrent JS engines. If you have more than 25 concurrent requests, the request needs to wait in a queue until one of the engines is available.

> Have you done any benchmarks on the difference between rendering the same type of content with Razor and React?

I haven't yet.

> In your own view, would you be comfortable using this for a business critical site with moderate to heavy load?

Yes, as long as you load test it :)

**Comment by andersekdahl** [comment]
I didn't change anything, just downloaded through NuGet and ran it. The limit of 25 engine instances should be somewhat responsible of how far behind Razor it was since I set the concurrency to 100 in AB.

I should also say that I installed React.NET in a project that we are going to ship in a few months that performs nowhere near as fast as my Razor example (since it does a lot of "real work" like database calls etc). And when I measured that, React.NET with some componenets rendering server side only slowed down the benchmark by 1/20.

What's your take on https://github.com/Offroadcode/SuperchargedReact.Net? It claims to be faster because it doesn't use an engine pool. To me that sounds like using Node.js without the cluster module. And since the React rendering is syncronous I'm not sure how much you benefit by using just one engine instance.

**Comment by PeteDuncanson** [comment]
@andersekdahl we wrote SuperChargedReact off the back of trying to get React.Net in production. During our testing we found V8 was holding on to some unmanaged memory every time we ran the page (due to global vars we had in our JS rather than anything React.NET was doing). We tried digging it to the why and how to fix it (trigger garbage collection basically) but found too many levels of abstraction (all of which are for good reason) for a quick enough turn around for go live so chose to write our own. The outcome of which is SuperChargedReact. Its fast purely because it does away with the idea of handling multiple JS engines so we can tune it to run as fast as possible and leverage all the performance the V8 runtime can give us. 

The lessons we learnt we are hoping to feed back into React.NET as time allows as I think its a great project and very noble to try to support so many OS's and its a great body of work.

Regarding the lack of pooling in SuperChargedReact, we us the recommend way of spinning up a new instance of V8 using ClearScripts own tips for performance and its so fast I can't see the benefit to trying to pool it as yet. Its certainly something we could add but in our tests its simply not been needed.

We will be continuing to develop SuperChargedReact for our needs but will be feeding back what we learn into React.NET to make it an even better product than it already is.

**Comment by andersekdahl** [comment]
@PeteDuncanson Thank you for the clairification! I'll definitely check out SuperChargedReact!

**Comment by Daniel15** [comment]
Closing this out since it's just a question, but please feel free to continue the discussion if you like.

@PeteDuncanson I'm still considering dropping JavaScriptEngineSwitcher and depending entirely on V8, which would bring a lot of the benefits of your Supercharged project.

**Comment by PeteDuncanson** [comment]
@Daniel15 our first site running on SuperChargedReact goes live today! Will be keeping an eye on it and feeding back. Still keen on doing some PR's with our ideas/changes in for React.Net but go live has gobbled up all my spare CPU cycles :)

**Comment by yrki** [comment]
Hi @PeteDuncanson - How has Supercharged been working in your live environment? I've just been running a load test with 1000 users for 3 minutes on React.Net, and it seems to get a lot of JSPoolExhaustExceptions. Have you done any load testing with SuperChargedReact?

**Comment by Daniel15** [comment]
@yrki

> I've just been running a load test with 1000 users for 3 minutes on React.Net, and it seems to get a lot of JSPoolExhaustExceptions.

Default pool size is 10 engines at startup and 25 engines maximum,  to ensure it doesn't consume an excessive amount of memory. That's most likely the bottleneck in your testing. You'll need to increase those for higher concurrency (`SetStartEngines` and `SetMaxEngines` in your `ReactConfig`)

**Comment by Reminouche** [comment]
Any news about a real benchmarking between razor, react.net (with different engine configurations and limits) and SuperChargedReact ?

**Comment by PeteDuncanson** [comment]
Hi Guys,

We did a lot of performance testing on React.Net which spawned the need for SuperChargedReact but that was nearly 2 years ago. SuperCharged does enough for our needs, sits on 3 servers and is plenty fast enough chewing through 500K of JS running our booking engine for a travel company. We've not touched it for a while simply because its not needed anything doing to it. The docs are certainly limited which we need to work on. Its currently running that site with ReactRouter v1 but with React Router v4 out I want to make some changes there as thats currently a bottle neck for us getting out site upgraded with React. 

Thanks to "crazy internet time" that site is already super old at 18 months but all that "old out of date tech" we chose then is still doing an amazing job and now we can start upgrading it all bit by bit.

Some folks have raised some crazy bench marks (as ever) and in those cases I'd suggest folks do their own testing to make sure either solution fits your needs. The up shot is SuperCharged works for our need and our requirements and hasn't given us a hiccup. React.Net is also awesome work (far more supported and documented than ours) so I would include that in any tests you want to do.

Biggest differences between the two solutions are that:
* We target only V8 for speed, React.Net has always aimed to be engine agnositic so it can run on anything.
* We spin up one engine on start up and then ask that for a new context for ever single request. This is documented as being the fastest way to get a clean instance and the nicest on memory as GC can just throw away the whole engine once done. Its not as fast as having a pool but we found the pools just grew in memory usage in our testing which causes a lot of additional code to manage it and some unexpected results/performance. Throwing it away is a touch slower but pragmatic to debug as "it always works".
* Daniel has been supporting, commenting, improving his library the whole time and I can't see that stopping. If you meet him you owe him a beer (I owe him dinner). We are lazy asses and stop once its good enough (which in our case was running a multi-million pound site at "damn thats quick" speeds), simple as that. Our support of SuperCharged up to date has been "flakey" as we are busy either earning money at our day jobs or raising our kids. So currently if you want supported solution Daniel is the best shot.

Any more questions let me know and I try to answer then :)

Cheers

Pete

**Comment by RichardWright** [comment]
I hate to resurrect this,  but as it is now 2018 does anyone have any updated figures?

**Comment by Taritsyn** [comment]
@RichardWright Now there is a [more recent discussion](https://github.com/reactjs/React.NET/issues/382).

**Comment by RichardWright** [comment]
@Taritsyn thanks
