### ISSUE TITLE
Question: is it possible to use existing react components with this library?

### ISSUE THREAD

**Issue by fpw23** [reactjs/React.NET#162]
There are a number of existing components out there on site like this: 

https://react.parts/web

Is is possible to use these existing components with ReactJS.net? 

The component I am most interested in is this:

https://github.com/insin/newforms

I tried just including the javascript file in the ReactConfig addscript but it did not work, their example uses require to get a base javascript class and that does not exist in the server side js environment, here is the exception:

> An exception of type 'React.Exceptions.ReactScriptLoadException' occurred in React.dll but was not       handled in user code
> Additional information: Error while loading "~/Scripts/FormTest.jsx": ReferenceError: require is not  defined

and here is the FormTest.jsx

    var forms = require('newforms');

    var SignupForm = forms.Form.extend({
    username: forms.CharField(),
    email: forms.EmailField(),
    password: forms.CharField({ widget: forms.PasswordInput }),
    confirmPassword: forms.CharField({ widget: forms.PasswordInput }),
    acceptTerms: forms.BooleanField({ required: true })
    });

    var Signup = React.createClass({
    render: function () {
        return <form onSubmit={this._onSubmit}>
              <forms.RenderForm form={SignupForm} ref="signupForm"/>
             <button>Sign Up</button>
          </form>
    }
    });

**Comment by jslatts** [comment]
Yes, you can use existing components in React.NET. Though, you need to be careful that they don't have any browser dependencies such as a reference to window (even then you can use React.NET to bootstrap the component client side and skip the server side render).

The require statements mean the module is designed for a CommonJS environment (like Nodejs), which React.NET does not provide for you. You will need to precompile your Javascript code using a module bundler like Browserify or Webpack, which will create a single Javascript file that includes all the dependencies for the module you are trying to load. 

You probably want to do this whether you use React.NET or not. Most (all?) of those components are going to be distributed from NPM as Node modules and will freely use other Node modules as dependencies (more require statements) so using a bundler is pretty much expected.

**Comment by Daniel15** [comment]
@jslatts nailed it. ReactJS.NET does not provide a CommonJS-like environment. You will need to use Browserify or Webpack to make any `require()` statements work.

In the case of the newforms library you linked to, there's actually a standalone build in the `dist` directory in the repo (see the [Browser bundle](https://github.com/insin/newforms#browser-bundle) section of its readme). In theory, you could actually load this `newforms.js` file in ReactJS.NET and then use the `forms` global in your app code (ie. without the `require` statement) without having to use a module bundler. Its readme says that it's "isomorphic", which means it should work for server-side rendering.

Personally I'd suggest learning about Webpack, it's pretty awesome. You can see [React.Sample.Webpack](https://github.com/reactjs/React.NET/tree/master/src/React.Sample.Webpack) for a sample project that uses ReactJS.NET and Webpack together.

I'm going to close this issue since it's just a discussion, but feel free to continue commenting if you have any further questions :)

**Comment by fpw23** [comment]
Wow, you were right, webpack really is awesome!  I got a demo working that is based off your webpack demo, it is using the newforms and newforms-bootstrap packages!!  Server side rendering works really well!  here is a [link](https://github.com/fpw23/ReactDemo) to it.  I do have some questions though:

1) in my demo I was able to create a folder hierarchy for my SignUp.jsx file by placing it in a sub folder named common.  I would want to do this to keep things tidy in a large project, kind of like namespacing, but in my index js file when I export it looks like everything is at the same level.  Is there a way to have what I export match my folder structure so that it all lines up?

2) the webpack build creates two files, one for server and one for client and in the docs you say to put only server side stuff in the server one and client side in the client one.  If I am doing server side rendering wouldn't I need everything in both anyways?  If I render on the server I still need to have that same js on the client to make it all work correct?

**Comment by Daniel15** [comment]
> If I am doing server side rendering wouldn't I need everything in both anyways? If I render on the server I still need to have that same js on the client to make it all work correct?

Yes, you need all the server-side JS on the client-side, but the reverse isn't true. You'll probably use at least some libraries client-side that can't run server-side (for example, any scripts that use AJAX, DOM, or `window`). That's why I suggest creating two separate bundles. Alternatively you could create a "shared" bundle and a "client" bundle - In that case you'd load the shared one server-side, and **both** the shared one **and** the client one server-side. It's simpler to just have two complete bundles though.

> Is there a way to have what I export match my folder structure so that it all lines up?

Hmm, you mean in the server-side bundle? Not sure, I'd need to think about this more. I still haven't thought much about ReactJS.NET + CommonJS modules through bundlers like Webpack. Perhaps I need better CommonJS support in ReactJS.NET to better handle modular JS files.

**Comment by PeteDuncanson** [comment]
As the bundle would be running on the server I tend to be pragmatic and not care if its got client-side stuff in. I tend to use only code thats in CommonJS format (ie just about anything built to run on Node.js). For Ajax stuff I use SuperAgent which plays nice. Thanks to Danels shims file which creates some global vars that try to keep most stuff working. If I do get anything "tricky" that needs to be hidden from the server then I just wrap it in a if ( typeof window == "undefined" ) {} check.

Again as its running on the server you don't have the size to worry about and parsing JS is insanely fast (even faster if you engine can save the compiled script like ClearScript can) so I don't really worry about it and just use the one bundle for both client and server.

Regarding the namespacing (assuming I've understood you correctly) this is mostly handled by the require statements used to pull in your various components:

```
var myNav = require("./navigation/fatMenu.jsx");
```

What is available depends on what you assing to module.export in your component file.

```
var FatMenu = React.createComponent({
  render: function() {
    return <p>Working</p>;
  }
} 

module.exports = FatMenu;
```

This works fine until you have several related components in one CommonJS file in which case you end up doing things like this:

```
var fatMenu = require("./navigation/menus").FatMenu;
var mobileMenu = require("./navigation/menus").MobileMenu;

// or alternatively

var Menus = require("./navigation/menus");
var fatMenu = Menus.FatMenu;
var mobileMenu = Menus.MobileMenu;
```

If you want to actually namespace your components when you use them you can do that too:

```
// Declared up top somewhere
var Menus = require("./navigation/menus");

var Header = React.createComponent({
  render: function() {
    return <Menus.FatMenu />
  }
}
```

So lots of options, if thats not what you meant let me know and I'll take another stab at it.
