### ISSUE TITLE
reactEnvironment.Babel.Transform does not work on Azure

### ISSUE THREAD

**Issue by PrimeObjects** [reactjs/React.NET#208]
Hi,

I'm using the codes below to convert js content into Babel transformed content. It works fine on my local server but it returns "Expected;identifier" in Exception.Message on Azure. Any idea?

var reactEnvironment = React.AssemblyRegistration.Container.Resolve<React.IReactEnvironment>();
 content =  reactEnvironment.Babel.Transform(content);

Thanks
Gary

**Comment by Daniel15** [comment]
The issue may be that it's using the V8 JS engine locally, but the MSIE JS engine on Azure. Basically it tries to use V8 by default, but falls back to the MSIE engine if loading V8 fails for some reason. I do know that some people are successfully using ReactJS.NET on Azure, so it should be possible to get it working. Try calling `.SetAllowMsieEngine(false)` in your `ReactConfig`, then publish to Azure again and see what exception you get.

As a side note, from ReactJS.NET 2.1 onwards you can use `ReactEnvironment.Current` as a shortcut for `React.AssemblyRegistration.Container.Resolve<React.IReactEnvironment>()` :smile:

**Comment by PrimeObjects** [comment]
no luck, got different error though "Unable;to;resolve;n:React.ReactEnvironment". I think there's no V8 JS engine at all on Azure server stack? My friend, please make it work on Azure, it is important to the success of ReactJs.net.

code in my startup.cs

app.UseReact(config =>
            {
                config.SetReuseJavaScriptEngines(true);
                config.SetAllowMsieEngine(false);
            });

**Comment by PrimeObjects** [comment]
Hi Daniel,

Any solution yet? Can we make MSIE JS engine as the default and give it a try? How to configure to enforce it use IE?

Thanks
Gary

**Comment by Daniel15** [comment]
> How to configure to enforce it use IE?

You can delete the ClearScript DLLs to force it to use MSIE.

**Comment by PrimeObjects** [comment]
Where is the dll? I do not think I can delete anything on Azure server.

**Comment by john-cheesman** [comment]
I'm having the same issue locally. I've got the `ClearScript.V8` folder at the project root but looking at the stack trace the error is coming from `MsieJavaScriptEngine`.

I've also got `System.Web.Optimization.React` installed and I get the same error at `@Scripts.Render()` in the view when trying to bundle `.jsx` files.

Any ideas?

**Comment by jvdenning** [comment]
To check what engine is loaded (in an ASP.NET C# web app) and which are available you can run the attached code and render the output in the mechanism of your choice (log it, output it to a web page).
We got ClearScript.V8 running on Azure by ensuring the ClearScript.V8 folder that comes with React.NET makes it to the server (both in the root of the web app and in the bin directory where the build puts it) - I couldn't use any ClearScript.V8 assemblies/DLLs that came from any other source.

However we are currently getting frequent but transient errors related to timeouts getting a JS Engine from the Pool or Potential Stack Overflow exceptions from the ClearScript.V8 code (which in turn is due to what the ClearScript dev called "blank exceptions" from V8...
[JSEngineDetectionSnippet.txt](https://github.com/reactjs/React.NET/files/82563/JSEngineDetectionSnippet.txt)

**Comment by samppis** [comment]
Here's how to get ReactJS.NET running in Azure using the V8 engine: http://www.samulihaverinen.com/web-development/dotnet/2016/01/19/how-to-run-clearscript-v8-javascript-engine-in-azure/

I'll try to write a documentation page for running ReactJS.NET in Azure once I get the Jekyll site to build locally.

**Comment by PrimeObjects** [comment]
Great, I will try it. Thank you Samppis!!!

**Comment by Daniel15** [comment]
Closing this out now that ReactJS.NET 2.2 runs on Azure and @samppis added this documentation page: http://reactjs.net/guides/azure.html
