### ISSUE TITLE
gulpfile.js and files from Resources folder in 2.2.0

### ISSUE THREAD

**Issue by vkrol** [reactjs/React.NET#222]
Hello.

When I install React.Core package from NuGet, the gulpfile.js and files from Resources folder have been added to the my project. Why is this happening? Do I need really these files? I cannot find anything about it in the documentation.

Thanks!

**Comment by WirthAware** [comment]
As far as i understand it correctly you can now tell reactjs.net to load your own reactjs version.
If you still want to use the React version from react.js.net you don't need these files. 
If you want to use reactjs from e.g. npm this will help you to bundle the reactjs version.
These files are just helper starting points to do so. 
And you have to tell your ReactConfig that you are loading reactjs by ding:

            ReactSiteConfiguration.Configuration
                .SetLoadReact(false)

**Comment by Daniel15** [comment]
Hmm, that's to supposed to happen! You don't need those files at all. What version of Visual Studio are you using, and what version of ASP.NET?

Sorry for the delay in replying, I was on vacation.

**Comment by sfadeev** [comment]
These files comes from folder `content` from React.Core.2.2.0.nupkg, this is the expected behavior for `content` files - Nuget include content of `content` folder to project while installing packages.

If these files are completely not required in end projects using React.Net (I've checked, seems works fine without them) they should be excluded from .nupkg. Simple way to do so is to mark these files with Build Action `None` in project React.Core (right now files marked with Build Action `Content`).

**Comment by Daniel15** [comment]
Oh yeah, that sounds like a mistake. I'll fix this up soon. Thanks :)

**Comment by Daniel15** [comment]
Release ReactJS.NET 2.2.1 which fixes this. Thanks for the bug report!
