### ISSUE TITLE
Can't use EmbeddedResourceFileSystem with React.Owin

### ISSUE THREAD

**Issue by Pondidum** [reactjs/React.NET#223]
It doesn't seem possible to use React.Owin with an `EmbeddedResourceFileSystem` (or anything, other than `PhysicalFileSystem`.

``` c#
app.UseBabel(new BabelFileOptions
{
    StaticFileOptions = new StaticFileOptions
    {
        FileSystem = new EmbeddedResourceFileSystem(Assembly.GetExecutingAssembly(), "Sample.Host.content")
    },
    Extensions = new[] { ".jsx" }
});
```

Rendering any jsx file results in the following exception:

```
Object reference not set to an instance of an object.
   at React.Owin.EntryAssemblyFileSystem.MapPath(String relativePath) in D:\dev\downloaded-src\React.NET\src\React.Owin\EntryAssemblyFileSystem.cs:line 22
   at React.FileSystemBase.ReadAsString(String relativePath) in D:\dev\downloaded-src\React.NET\src\React.Core\FileSystemBase.cs:line 52
   at React.Babel.TransformFileWithSourceMap(String filename, Boolean forceGenerateSourceMap) in D:\dev\downloaded-src\React.NET\src\React.Core\Babel.cs:line 118
   at React.Babel.TransformFile(String filename) in D:\dev\downloaded-src\React.NET\src\React.Core\Babel.cs:line 89
   at React.Owin.BabelFileSystem.BabelFileInfo.<>c__DisplayClass3_0.<.ctor>b__0() in D:\dev\downloaded-src\React.NET\src\React.AspNet\BabelFileSystem.cs:line 160
   at System.Lazy`1.CreateValue()
```

You can kind of fix the error by adjusting `BableFileInfo`'s _content from:

``` c#
_content = new Lazy<byte[]>(
    () => Encoding.UTF8.GetBytes(_babel.TransformFile(fileInfo.PhysicalPath))
);
```

To this:

``` c#
_content = new Lazy<byte[]>(() =>
{
    using (var stream = fileInfo.CreateReadStream())
    using (var reader = new StreamReader(stream))
    {
        var content = reader.ReadToEnd();
        var transformed = _babel.Transform(content);

        return Encoding.UTF8.GetBytes(transformed);
    }
});
```

But while this works, it doesn't add the transformed content to the transform cache.

I'm not really certain where to go from here to be honest...

**Comment by Daniel15** [comment]
I don't have a lot of experience with OWIN or its filesystem implementations. @mandrek44 Do you have any suggestions here?

> But while this works, it doesn't add the transformed content to the transform cache.

I'm not entirely sure how to cache something based on input from a stream, as you can't really get a 'hash' of the stream. Does `EmbeddedResourceFileSystem` still have a concept of a file name? If so, we could have a separate cache that's keyed off the filename and have a `TransformStreamWithCacheKey(Stream stream, string cacheKey)` method on `IBabel` to handle caching it.

**Comment by taspeotis** [comment]
I have this issue with ASP.NET 5 as well (using RC1).

I think the solution would be to have `FileSystemBase` use the same `FileProvider` as `StaticFileOptions`. Or, as the original post points out, `FileInfo` has `CreateReadStream`. Right now `FileSystemBase` just calls `File.ReadAllText` which goes for the physical file system.

> Does EmbeddedResourceFileSystem still have a concept of a file name

[The `EmbeddedResourceFileInfo` class from ASP.NET 5](https://github.com/aspnet/FileSystem/blob/dev/src/Microsoft.Extensions.FileProviders.Embedded/EmbeddedResourceFileInfo.cs) does not have a unique name, it has a `Name` property which is just the file's name.

> you can't really get a 'hash' of the stream

Just hash the stream's content? `FileSystemBase` is reading the entire file anyway.

**Comment by taspeotis** [comment]
If we agree that hashing the stream's content is acceptable let me know and I'll try and make a PR out of it.

**Comment by Daniel15** [comment]
> If we agree that hashing the stream's content is acceptable let me know and I'll try and make a PR out of it.

I think that makes sense. Feel free to send a PR my way!

> Also, now that I've looked at it, EmbeddedResourceFileSystem returns null for PhysicalPath so it's probably a reasonable performance optimization to key the cache by fileInfo.PhysicalPath ?? StreamContentHash()

Sounds good. Please add a unit test for this :smile:

**Comment by taspeotis** [comment]
I started some work, the bulk of which you can view [here](https://github.com/taspeotis/React.NET/commit/f6540a4a4cc35e9d9da6d12432c1433856dfcf6b#diff-48c6a1d5d28127a8874fc8f851070b54R101). (Disregard the formatting for now; I used spaces instead of tabs.)

After poking around a bit, I think this needs a bit more consideration. As far as my *extremely nascent understanding* of ASP.NET 5 goes, `IFileSystem` is a bit of an anachronism.

Instead of `IFileSystem` the library should just use an `IFileProvider`. This would be implemented library-wide along the lines of `IReactSiteConfiguration.FileProvider` (and render the `FileProvider` property on `BabelFileOptions` obsolete).

By way of example: consider `IFileSystem.MapPath`. Right now `AspNetFileSystem` does the following:

```
public override string MapPath(string relativePath)
{
	relativePath = relativePath.TrimStart('~').TrimStart('/');
	return Path.Combine(_hostingEnv.WebRootPath, relativePath);
}
```

An embedded resource doesn't have a path to map to. At best it could be something like `YourAssembly.EmbeddedResources.YourFile.jsx`: the [manifest resource name](https://msdn.microsoft.com/en-us/library/system.reflection.assembly.getmanifestresourcenames(v=vs.110).aspx).

For non-physical file providers, there's no such thing as a physical path. Note that without a physical path that `IFileInfo` objects don't have an identity beyond the the hash of their stream. (If an `IFileInfo` has a non-`null` `PhysicalPath` then that's its identity.)

If you can carry around the virtual path *in addition to the `IFileProvider`* then you have an identity always.

(The ASP.NET `IFileProviders` are [here](https://github.com/aspnet/FileSystem/tree/dev/src).)

So to do this properly, `IFileSystem` might have to be ripped out. `MapPath` certainly would have to be.

(ReSharper counts 18 references to `IFileSystem.MapPath`. Most of them are in `FileSystemBase` but outside of that it's used for things like hash keys.)

Rather than continue on I'd rather defer to someone else's judgement.

**Comment by dustinsoftware** [comment]
Since it's been over a year, I'm closing issues for future tasks like this that aren't actively being worked on, but would be open to adding support for this!

#655

**Comment by samblackburn** [comment]
We've found that the issue affects all calls to `TryGetFileInfo()` with a forward slash in the resource name.

This is the workaround class we wrote to avoid the problem:
``` c#
    /// <summary>
    /// This class is a workaround for a regression in <see cref="EmbeddedResourceFileSystem"/>
    /// somewhere between v2.1 and v4.2.2.
    /// </summary>
    /// <remarks>
    /// It can no longer retrieve individual resources with a forward slash in the name.
    /// It can also no longer list subdirectories, which means the only way to retrieve
    /// a resource with '/' in the name is to list the entire root directory.
    /// We therefore cache this listing (since embedded resources are immutable)
    /// and do the lookup ourselves.
    /// </remarks>
    public class EmbeddedResourceFilesystemWorkaround : IFileSystem
    {
        private readonly IEnumerable<IFileInfo> m_Listing;

        public EmbeddedResourceFilesystemWorkaround()
        {
            new EmbeddedResourceFileSystem().TryGetDirectoryContents("/", out m_Listing);
        }

        public bool TryGetFileInfo(string subpath, out IFileInfo fileInfo)
        {
            var withoutSlash = subpath.TrimStart('/');
            fileInfo = m_Listing.SingleOrDefault(l => l.Name == withoutSlash);
            return fileInfo != null;
        }

        /// <summary>
        ///  This method never appears to be hit.
        ///  We therefore haven't implemented non-root lookups.
        /// </summary>
        public bool TryGetDirectoryContents(string subpath, out IEnumerable<IFileInfo> contents)
        {
            contents = m_Listing;
            return subpath == "/";
        }
    }
```
