### ISSUE TITLE
The dependency JSPool >= 0.4.1 could not be resolved.

### ISSUE THREAD

**Issue by westdavidr** [reactjs/React.NET#269]
I just started getting this error today. I'm not sure how to proceed.

**Comment by JesperTreetop** [comment]
I'm getting this too while using a (full) .NET Framework with this declaration in project.json: `"frameworks": { "net452": { "imports": [ "dnx451" ] } }`

**Comment by Daniel15** [comment]
What version of ASP.NET 5 are you using? I've only tested with RC1. I know
RC2 came out recently, perhaps it has some breaking changes.

Sent from my phone.
On May 18, 2016 11:08 PM, "JesperTreetop" <notifications@github.com> wrote:

I'm getting this too while using a (full) .NET Framework with this
declaration in project.json: "frameworks": { "net452": { "imports": [
"dnx451" ] } }

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/reactjs/React.NET/issues/269#issuecomment-220020320>

**Comment by JesperTreetop** [comment]
I'm using RC2. Looking at this and trying to isolate anything strange, I think it may be that JSPool's NuGet package uses the Client profile of .NET 4.0.

**Comment by Daniel15** [comment]
Try cloning the ReactJS.NET repo, upgrading all dependencies from RC1 to
RC2, and see if that helps.

**Comment by ShikiGami** [comment]
I've been trying all day to make ReactJs work in RC2, but there is a big problem with dependencies not being found. I got it to compile, but then it doesn't find the namespaces at runtime.

**Comment by ShikiGami** [comment]
The JSPool Error happens, because now in RC2 it is trying to resolve an already resolved dependency in React.AspNet.

To make it work, simply delete the JSPool dependency line from .\src\wrap\React.Core\project.json

**Comment by frankbaum** [comment]
Has this been resolved in Nuget? I can not clone the project I can only pull it through nuget due to proxy/firewall - this is an MVC 4 project and the JSPool dependency is preventing install.

**Comment by Daniel15** [comment]
@frankbaum - I've only seen this issue for ASP.NET 5 (MVC 6) projects, not MVC 4. What is the exact error message you're seeing?

**Comment by Daniel15** [comment]
I haven't seen any reports of this in a while, so I suspect there was some bug in NuGet. Please let me know if you still encounter it.
