### ISSUE TITLE
Passing DateTime in Html.React<T>()

### ISSUE THREAD

**Issue by kaa** [reactjs/React.NET#276]
I would like to pass a `DateTime` in the properties passed to `@Html.React<T>()`. At the moment the value is serialized, which makes perfect sense, according to the `JsonSerializationSettings` that can be configured through the `IReactSiteConfiguration` interface.

I do however find that this creates a slight disconnect for me between the props i pass server side and client side. On the client side I would pass a javascript `Date` object in the properties and use that straight off, but on the server side this value is serialized to a string and I would need to parse it into a `Date` before using it.

I realized that the way component rendering is currently implemented in [src/React.Core/ReactComponent.cs](https://github.com/reactjs/React.NET/blob/8a02fc775cdf6cdada0c134ff3bbbce77f114ef7/src/React.Core/ReactComponent.cs#L162) I probably could set `JsonSerializerSettings` up with a custom converter that would just output a `new Date(...)` expression and it would automatically be parsed, and only for server side rendering.

My question is, does this make sense, and am I alone with this problem?

**Comment by tmct** [comment]
This has also been a problem for us - C# DateTimes serialise to js strings instead of Dates.

For now we're working around this by passing the ToString() of the DateTime, but it would be nice for React.NET to support these types!

**Comment by Daniel15** [comment]
It seems like you should be able to use `JavaScriptDateTimeConverter` for this: http://www.newtonsoft.com/json/help/html/datesinjson.htm. You can set the `JsonSerializerSettings` through your ReactSiteConfiguration (the `SetJsonSerializerSettings` method). This seems like a question about JSON.NET (Newtonsoft.Json) rather than ReactJS.NET specifically.

I'm going to close this out as it's a discussion, but feel free to leave a comment if you have any further questions about this :smile:
