### ISSUE TITLE
Failed to load the ClearScriptV8 assembly, because the directory does not exist

### ISSUE THREAD

**Issue by tim-cools** [reactjs/React.NET#295]
Hi,  I try to get React.NET server side rendering working and I receive following error:

```
DirectoryNotFoundException: Failed to load the ClearScriptV8 assembly, because the directory 'C:\_\xxx\git\src\xxx.Web\bin\Debug\net46\win7-x64\ClearScript.V8' does not exist.
get_Environment

JsEngineLoadException: During loading of V8 JavaScript engine error has occurred.	
See more details:

Failed to load the ClearScriptV8 assembly, because the directory 'C:\_\xxx\git\src\xxx.Web\bin\Debug\net46\win7-x64\ClearScript.V8' does not exist.
get_Environment

TargetInvocationException: Exception has been thrown by the target of an invocation.
get_Environment
...
```

I included JavaScriptEngineSwitcher.V8 in my project.json:

```
    "JavaScriptEngineSwitcher.V8": "1.5.5",
    "React.AspNet": "2.5.0"
```

But it doesn't seem to fetch the ClearScript.V8 folder. 

I also installed the C++ VS2013 redistr. Do you have any idea where to look further? 

Also, I read somewhere you use the VroomJS on linux in production. How do you configure React.NET to use VroomJS?

Thanks in advance!

**Comment by Daniel15** [comment]
The DLLs are automatically copied over with 'classic' ASP.NET 4.x, but not with ASP.NET Core. I had another look at ClearScript, and the only reliable way I could find to copy over the ClearScript DLLs in an ASP.NET Core project without checking them into the project repo was to have an ugly `xcopy` postcompile script in `project.json`:
```
  "scripts": {
    "postcompile": [
      "xcopy /Y C:\\Users\\Daniel\\.nuget\\packages\\JavaScriptEngineSwitcher.V8\\1.5.2\\content\\ClearScript.V8 %compile:RuntimeOutputDir%\\ClearScript.V8\\*"
    ]
  }
```

This is super-ugly since it has the local NuGet package path hard-coded, but it seems to work fine. Alternatively, just copy them to your project's root directory then use `copyToOutput` like @anatolitrifonov  mentioned above.

Doing something like that and also adding `.SetAllowMsieEngine(false)` to the config should work to avoid this issue.

> Also, I read somewhere you use the VroomJS on linux in production. How do you configure React.NET to use VroomJS?

It's automatically used on Linux.

**Comment by Daniel15** [comment]
Blogged about this here: http://reactjs.net/2016/08/protected-memory-exceptions-and-dotnet-core.html. Basically, for ASP.NET Core, you need to configure your `project.json` to copy over the `ClearScript.V8` directory on build, as it's no longer done automatically. This is just temporary, as JavaScriptEngineSwitcher 2.0 will fix it.

Closing this out, but please feel free to reopen if you have further questions about it! Thanks :smile:
