### ISSUE TITLE
How to disable[.NET] warnings?

### ISSUE THREAD

**Issue by imperat0r** [reactjs/React.NET#316]
I tryied setting NODE_ENV=production on my Windows server. I was really really exited about this project but today little bit dissapointed with performance in production. I think it will help with performance on server side if I disable some checks in code which result in warnings, but it seems setting NODE_ENV does not take effect,

**Comment by Daniel15** [comment]
Wow, good catch! Looks like I forgot about this and there's still a todo in the code 😒 

https://github.com/reactjs/React.NET/blob/master/src/React.Core/JavaScriptEngineFactory.cs#L109-L110

You can try building your own build of ReactJS.NET if you like. Clone this repo, modify that line of code to load `react.generated.min.js` rather than `react.generated.js`, then run `dev-build.bat` to build.
