### ISSUE TITLE
ReactServerRenderingException: Error while rendering...

### ISSUE THREAD

**Issue by tinngv** [reactjs/React.NET#383]
Hi,

I use server side rendering and it throws this exception:

```
An unhandled exception occurred while processing the request.

ReactServerRenderingException: Error while rendering "xxx" to "react_qFq3a2hLEmMM3uuMeCVZA": Script threw an exception: Minified React error #109; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=109&args[]=xxx for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Line: 0
Column:0
```

Please help

**Comment by jslatts** [comment]
Have you decoded the react error per the message? https://facebook.github.io/react/docs/error-decoder.html?invariant=109&args[]=xxx

It appears that you have a react component that is not returning a valid react element.

**Comment by Daniel15** [comment]
You can use the debug version of React by calling `.SetUseDebugReact(true)` in your config. This will give you the full error message.

**Comment by tinngv** [comment]
Thanh you

**Comment by fgaleano** [comment]
I'm getting the same error on my project using Webpack.

My ES6 component looks like this:

```
import React from 'react';

const PageContent = (props) => {
    let myName = 'Fernando';
    return (
        <div>
            Hello, {myName}! From {props.user}
        </div>
    );
}

export default PageContent;
```

After I bundle the code using Webpack, `PageContent` looks like this on the ES5 output:

```
var _react = __webpack_require__(22);

var _react2 = _interopRequireDefault(_react);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var PageContent = function PageContent(props) {
    var myName = 'Fernando';
    return _react2.default.createElement(
        'div',
        null,
        'Hello, ',
        myName,
        '! From ',
        props.user
    );
};

exports.default = PageContent;
```

I enabled debug mode and what I'm getting in Visual Studio is the incorrect element message, saying it was expecting `function` or `string` but got `object` instead.

From the ES5 code it looks like `PageContent` is a function and its return should be a string (output of `createElement`), so I'm not sure what is wrong here.

Is there anyway to see what .NET is getting from all of this? I'm using WebForms, if that helps at all.

I suspect my Webpack configuration might need some tweaking but so far I think I've done everything. I really need to to this with ES6 so that's why I'm not following the official example.

Any ideas? Thanks!

**Comment by fgaleano** [comment]
Huh, if in my component I changed this:

`export default PageContent;
`
to this:

`module.exports = PageContent;`

Things worked. Definitely something in my webpack configuration is messing things up. I wonder what...

**Comment by damanptyltd** [comment]
@fgaleano 
That solved my problem! However for cases when you need to use a class to access other methods like ComponentDidMount, how can  a class be used to bypass this issue?

@Daniel15  Was it ever determined why this wasnt working and what the real fix is?
