### ISSUE TITLE
webpackJsonp is not defined in server side rendering

### ISSUE THREAD

**Issue by svillamonte** [reactjs/React.NET#392]
Hey!
I have been following along the guide to make Webpack work with React.NET, and one of the requirements is to have third party libraries in a separate bundle. For this, I've made use of the CommonsChunkPlugin found at https://webpack.js.org/guides/code-splitting-libraries/.
Trying this setup with client side rendering seems to work alright, but can't still figure out how to do the same for server side rendering. I would always see the error `Error while loading "~/Scripts/build/bundle.js": ReferenceError: webpackJsonp is not defined`.
I'm fairly new to this Webpack world, but managed to realize that `webpackJsonp` variable is registered at the `window` level, which I'm guessing the server side rendering engines have no access to. Is this the case? Is there any workarounds for this issue?
Thanks a lot in advance!

**Comment by Daniel15** [comment]
> I'm fairly new to this Webpack world, but managed to realize that webpackJsonp variable is registered at the window level, which I'm guessing the server side rendering engines have no access to

Ahh, good catch. I guess Webpack code splitting isn't designed to be used in conjunction with server-side rendering 😢 

You're right that there's no `window` when doing server-side rendering. I wonder whether the Webpack team have any advice for this scenario.

**Comment by svillamonte** [comment]
Wow, that was fast. I'll keep on digging, but thanks a lot for your quick reply!

**Comment by jslatts** [comment]
My solution to this problem is to avoid using code splitting on the server. The problems it solves are not applicable to server side rendering. In fact, I do quite a few things differently on the server build, including using the null-loader to avoid dealing with certain packages that are problematic when there is no window object.

You can have two webpack configurations, one for the server (no code splitting) and one for the browser (go nuts). You can build them both at the same time like by exporting an array at the bottom of your webpack config.

    module.exports = [clientConfig, serverConfig]

Happy to answer any other questions related to webpack. We are using webpack, redux, react router, hot module reloading, and server side rendering with React.NET. It can all work fine together with a little work.

**Comment by svillamonte** [comment]
That was spot on @jslatts , thanks! Guess I need to read quite a lot of how Webpack works first, before trying to get these kind of things to work.
Would it be possible for you to share a public repo with all those tools living together, so we can have for future reference? Or at least your webpack.config.js file?
Anyways, thanks again to both of you!

**Comment by jslatts** [comment]
I have thought about writing up a blog post about getting this stuff all running together. It is hard to gauge how much interest there is with using this specific stack on React.NET.

Happy to share the webpack config though: https://gist.github.com/jslatts/f9dec699e8fd853590f520f62d5bf21a

I removed some of the totally extraneous stuff (legacy components, etc) to cut it down somewhat, but its pretty much what we use. One disclaimer, we aren't many/any production optimizations yet. There is some work to do around optimization. We aren't particularly worried about that at the moment.

**Comment by svillamonte** [comment]
Thanks again, that should prove handy!

**Comment by thebuilder** [comment]
Running React serverside in .NET is a synchronus action, so codesplitting doesn't work serverside.
But you can use code splitting in the clientside code, to only load components that you need. This does require a lot of setup and configuration of your codebase and build system, but it can be done! Currently working on a big project where all components are their own webpack chunk.

I created a task last year, about how this can be solved: https://github.com/reactjs/React.NET/issues/315

I ended up creating a custom .NET package, that just uses ReactJS.NET for the engine configuration, since we always use a precompiled `server.bundle.js`.

All my components have a two entry files - an `index.js` for static, and `importer.js` for async. 

**importer.js**
```js
/**
 * Small module that allows us to statically import the related module, while only
 * dynamically importing this small module with 'delayed-render.js'.
 */
export default () => import('./index')
```

Using `require.context` i then fetch the entry file based on the ENV.

**modulesMap.js**
```js
let modulesMap = null

function getModules() {
  if (!modulesMap) {
    modulesMap = {}
    if (process.env.SERVER) {
      const modules = require.context('./', true, /index\.js$/g)

      modules.keys().forEach(name => {
        const moduleName = name.replace(/\.\/(\w+?)\/index.js$/, '$1')
        modulesMap[moduleName] = modules(name)
      })
    } else {
      const modules = require.context('./', true, /importer\.js$/g)

      modules.keys().forEach(name => {
        const moduleName = name.replace(/\.\/(\w+?)\/importer.js$/, '$1')
        modulesMap[moduleName] = modules(name)
      })
    }
  }

  return modulesMap
}

export default function getModule(name) {
  if (!name) return null
  if (process.env.NODE_ENV === 'test') {
    // eslint-disable-next-line
    return require(`./${name}/importer.js`);
  }

  return getModules()[name]
}
```

I then use a `delayedRender` method clientside, to import all the components created by the server.

**delayedRender.js**
```js
import React from 'react'
import ReactDOM from 'react-dom'
import { logException } from '../utils/error-tracking'
import getModule from './modules-map'

/**
 * Call with list of server side rendered components when the app is ready.
 * Each component should contain the follow values: "name", "props" and "id".
 *
 * @param components {Array} List of components to render.
 */
export default function delayedRender(components) {
  return components.map(({ name, props, id }) => {
    const mod = getModule(name)
    if (mod) {
      /* Async import the required components when they are needed */
      return mod
        .default()
        .then(module => render(module.default, props, id))
        .catch(err => logException(err, { name, props, id, components }))
    }

    return Promise.reject()
  })
}

export function render(component, props, id) {
  const el = document.getElementById(id)

  if (component && el) {
    ReactDOM.render(React.createElement(component, props), el)
  } else if (!el) {
    throw new Error(`[delayedRender] Could not find element with id: '${id}'`)
  } else {
    throw new Error(`[delayedRender] Component not found for element with id: '${id}'`)
  }
}
```

I might do a writeup of our setup at some point, but it has a lot of moving parts and is not something that can just be added to public repo.

**Comment by Daniel15** [comment]
Thanks @jslatts and @thebuilder! I'm going to close this out as it's just a question rather than a bug, but feel free to add additional comments if you want to continue the discussion :)

**Comment by rshackleton** [comment]
I'm looking into using this and one of the main issues I am having is combining HMR and SSR together. I am able to build the assets beforehand and then run the website and everything works fine. However, when using webpack-dev-server with HMR the assets are not written to disk and therefore I get this error:

```
Could not find a part of the path 'C:\...\ReactTest\build\main.server.bundle.js'.
```

@jslatts, you mentioned having HMR and SSR working together, I've taken a look at your Gist but can't see any way of avoiding this issue other than using `webpack --watch` and losing HMR. 

Are you able to add entrypoint examples to your Gist as well?

Do you reference `react`, `react-dom` and `react-dom/server` in there?

**Comment by rshackleton** [comment]
Also the use of `@Html.ReactInitJavaScript()` means we cannot load scripts with `defer` or `async` as `ReactDOM` needs to be available - is there a workaround for this?
