### ISSUE TITLE
ReactInitJavaScript?

### ISSUE THREAD

**Issue by cuong-nguyen** [reactjs/React.NET#394]
Hello,

I am very new to React JS. I follow the article [here](https://reactjs.net/guides/server-side-rendering.html).
Can you guys tell me what is the purpose of **@Html.ReactInitJavaScript** method call?
I remove it and components still get rendered!
I see that with **@Html.ReactInitJavaScript** included, **<script>** tag get rendered in client _(to render initialisation scripts)._ What does it do?

Thanks!

**Comment by Daniel15** [comment]
With server-side rendering, the JavaScript is executed server-side and the results are sent down to the client. However, this is just static HTML. In order to make the component interactive, it needs to be initialised in JavaScript too. That's what `Html.ReactInitJavaScript` does - It runs the JavaScript required to initialize the components client-side.

**Comment by cuong-nguyen** [comment]
Thank you @Daniel15, it makes sense now.
