### ISSUE TITLE
Document how to debug through React.sln projects locally

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [reactjs/React.NET#460]
There are some build failures in one of my PRs (#459). It would be swell to step through the .cs in Visual Studio locally. When running F5 now, failures are listed as part of the build instead of runtime.

![image](https://user-images.githubusercontent.com/3335181/32405555-20c166a6-c125-11e7-973b-b945935a9910.png)

**Comment by Daniel15** [comment]
Yeah it's tricky because that comes from the MSBuild step for the sample project, which runs as a separate process. It can't run in the same build process as the MSBuild library is built as part of the build, so the file is locked during the main build.

You can temporarily comment out the `<TransformBabel />` node in `React.Sample.Mvc4\TransformBabel.proj`.

**Comment by dustinsoftware** [comment]
Closing issues older than a year, please re-open if you think this is still relevant.
