### ISSUE TITLE
React.Exceptions.ReactServerRenderingException

### ISSUE THREAD

**Issue by srdjanRakic** [reactjs/React.NET#490]
Trying to do server side rendering and I am getting this exception: 

React.Exceptions.ReactServerRenderingException: 'Error while rendering "FlightCacheContainer" to "react_HcrCWoESUqfx7Djz1TlEA": TypeError: Object doesn't support property or method 'toLowerCase'
   at renderDOM (React.Core.Resources.react.generated.js:4403:6)
   at render (React.Core.Resources.react.generated.js:4382:12)
   at read (React.Core.Resources.react.generated.js:4349:8)
   at renderToString (React.Core.Resources.react.generated.js:4607:4)
   at Global code (Script Document [12]:1:1)
Line: 4403
Column:6'

**Comment by srdjanRakic** [comment]
I still have this problem, mainly I think is when I use component into component with SSR. Does anyone have had this error before?

**Comment by saberone** [comment]
I'm having the same error right now. I tried 16.0 and 16.2.

**Comment by dustinsoftware** [comment]
Hi there, would you mind providing a code sample for the render method in
your component?

If you disable server render by passing clientOnly: true to the React.NET
call in your razor file, does your component render?

**Comment by gazab** [comment]
I had this problem until I added `module.exports = TheComponentClass;` at the end of my component files

**Comment by selected-pixel-jameson** [comment]
@gazab I agree that this is the root of the problem. I was following the example on https://reactjs.net/guides/webpack.html, but I think it's out of date possibly. I'm going to try to adapt my configuration to match what you are doing and see if that helps solve this problem.

**Comment by selected-pixel-jameson** [comment]
I finally got around this by making sure to do something similar to what @gazab mentioned. I also had to make sure that I was including references to react and any dependent modules. For example:

`import React from 'react'
import ButtonListSelector from '../ButtonListSelector'
import AddressBox from './AddressBox'

class AddressSelector extends React.Component {
.....
}

module.exports = AddressSelector`

After doing this with all of my classes I was able to get the page to initially render. However now I'm getting a console error in chrome. 

> 2425c9d4-9036-498a-0c74-08d53b3b74bd:56 Uncaught ReferenceError: Components is not defined
    at 2425c9d4-9036-498a-0c74-08d53b3b74bd:56

**Comment by bbsdddougla** [comment]
This problem is occurring in the generated react resource file on server-side for me. I'm using ChakraCore 1.8.1 for my JsEngine on ReactJs.Net 3.3.0. 

Setting [.SetUseDebugReact(true)](https://github.com/reactjs/React.NET/issues/383#issuecomment-285897348) shows that it occurs in ReactDOMServerRenderer.prototype.renderDOM:

```
Exception information: 
    Exception type: ReactServerRenderingException 
    Exception message: Error while rendering "Checkout.default" to "react_nkBwNivQ0qY35tfjZMKkQ": TypeError: Object doesn't support property or method 'toLowerCase'
   at renderDOM (React.Core.Resources.react.generated.js:4403:6)
   at render (React.Core.Resources.react.generated.js:4382:12)
   at read (React.Core.Resources.react.generated.js:4349:8)
   at renderToString (React.Core.Resources.react.generated.js:4607:4)
   at Global code (Script Document [3]:1:1)
Line: 4403
```

The call site is:
var tag = element.type.toLowerCase();

It appears that renderDOM won't get called without being passed a valid react element (in ReactDOMServerRenderer.protptype.render). So, type should indeed be a string, which should indeed support the method toLowerCase.

Somehow, an object is assigned to element.type at this point. 

What am I doing wrong?

**Comment by bbsdddougla** [comment]
I upgraded to React.Core 3.3.0 and this problem persists.

**Comment by bbsdddougla** [comment]
After trying V8, the problem persists, so it is likely not JsEngine-specific. When not rendering server-side the react components are rendered client-side as expected. V8 gives a slightly more descriptive exception, with the line that caused the error.
```
Exception information: 
    Exception type: ReactServerRenderingException 
    Exception message: Error while rendering "Checkout.default" to "react_o2ImMb0WwE2vERojOPVjNg": TypeError: element.type.toLowerCase is not a function
    at renderDOM (React.Core.Resources.react.generated.js:4403:29) -> 	    var tag = element.type.toLowerCase();
    at render (React.Core.Resources.react.generated.js:4382:24)
    at read (React.Core.Resources.react.generated.js:4349:20)
    at renderToString (React.Core.Resources.react.generated.js:4607:26)
    at Script Document [4]:1:16
```

**Comment by bbsdddougla** [comment]
In my server.js file, I needed to export `ReactDOMServer`. 

This server.js serves my components after rendering server-side:
```
import Checkout from "./components/Checkout"
import ReactDOMServer from 'react-dom/server'

global['Checkout'] = Checkout
global['ReactDOMServer'] = ReactDOMServer
```

This server.js returns a 500 error with the above stack trace:
```
import Checkout from "./components/Checkout"
import ReactDOMServer from 'react-dom/server'

global['Checkout'] = Checkout
//global['ReactDOMServer'] = ReactDOMServer
```

Why is that? Perhaps it should be obvious that the server-side library needs to be loaded globally to render server-side. Still, shouldn't this be registered globally server-side by the React.NET code? Did I turn it off in ReactConfig.cs?

```
public static void Configure()
{
 var reactSiteConfiguration = ReactSiteConfiguration.Configuration;
 
 reactSiteConfiguration.SetLoadReact(true);

 reactSiteConfiguration.SetLoadBabel(false);

 CompilationSection compilationSection = (CompilationSection)ConfigurationManager.GetSection(@"system.web/compilation");
 if (compilationSection.Debug)
 {
   reactSiteConfiguration
    .SetReuseJavaScriptEngines(false)
    .SetUseDebugReact(true);
 }

 foreach (var entryPointInfo in ReactEntryPointFiles)
 {
   reactSiteConfiguration.AddScriptWithoutTransform(entryPointInfo.ServerScript);
 }

 var chakraCoreJsEngineFactory = new ChakraCoreJsEngineFactory();
 JsEngineSwitcher.Instance.EngineFactories.Add(chakraCoreJsEngineFactory);
 var defaultJsEngineName = ChakraCoreJsEngine.EngineName;
 JsEngineSwitcher.Instance.DefaultEngineName = defaultJsEngineName;
}
```

I see that the name of the component in the generated react resource file (React.Core.resouces.react.generated.js) appears to be ReactDOMFiber instead of ReactDOMServer. Is that a change in the underlying library?

**Comment by dustinsoftware** [comment]
Try using `module.exports = yourComponent` instead of `export default` syntax, just to isolate what could be going wrong. It's possible that a module is being imported as `{ default: (your react component) }` someplace that still uses `require` instead of `import`. [This babel plugin](https://www.npmjs.com/package/babel-plugin-add-module-exports) will handle the `.default` export for you automatically. 

The webpack docs do need to be updated to use `import` instead of `require`, we'll get to updating that.

**Comment by trevorloflin** [comment]
For future reference, this error can also occur if you forget to qualify your component with the expose-loader container. In other words, if you're exposing the components with `'expose-loader?MyContainer!./MyFolder'` but calling it with `@Html.React('MyComponent', Model)`, you'll get this error. You need to use `@Html.React('MyContainer.MyComponent', Model)` instead.
