### ISSUE TITLE
Does Reactjs.Net supports Redux ?

### ISSUE THREAD

**Issue by nsivaji61** [reactjs/React.NET#513]
I wanted to create an application with react and redux store. Does Reactjs.Net supports redux? If Yes can i have some documentation?

**Comment by nsivaji61** [comment]
Thank you

**Comment by nsivaji61** [comment]
Did you get chance to update the sample for redux?

**Comment by chrisbarnes** [comment]
@dustinsoftware I'm also interested in seeing an example too if you have time. Thanks!

**Comment by dustinsoftware** [comment]
So there isn't really anything special you have to do to get Redux to work. Here's a gist that demo's the basics of wiring it up: https://gist.github.com/dustinsoftware/320c3877e3d4cb96e468eb3ecab9367a#file-commentsbox-redux-jsx-L113-L125

(The webpack sample in this repo will probably fail to run because I forgot to add in the necessary `prop-types` package when updating everything...I'll fix that)

I didn't put any effort into wiring up dispatching actions and testing that flow, but the server-render works fine, and you can see the global store getting passed in to the top level component.

It might be worth having a sample checked into this repo that demonstrates Redux since it's commonly used in large applications.

**Comment by dustinsoftware** [comment]
Closing since this question is answered, please feel free to re-open if you'd like some more help! 😄

**Comment by azharuddinsayed** [comment]
i have implemented reactjs.net with redux and getting error
JsScriptException: Script threw an exception.
JavaScriptEngineSwitcher.ChakraCore.JsRt.JsErrorHelpers.ThrowIfError(JsErrorCode errorCode)

JsRuntimeException: Invariant Violation: Could not find "store" in the context of "Connect(Login)". Either wrap the root component in a , or pass a custom React context provider to and the corresponding React context consumer to Connect(Login) in connect options.

can you please help me
Thanks in advance .

**Comment by dustinsoftware** [comment]
Sorry, I can’t help debug redux problems. You could try asking on stack
overflow. My first step would be to add redux to a fresh app using
create-react-app.

It’s also possible that this library doesn’t work with redux either anymore
due to a redux update; I haven’t investigated. There might be some
documentation somewhere that talks about how to set up SSR with redux. :)

**Comment by azharuddinsayed** [comment]
Can you please help me in one more case i have SSR and after getting the response from the server controller method on a button click i want to redirect to another page i am doing it like below ,please let me know is this the correct approach 
`fetch(`${this.props.submitUrl +
            "?userName=" +
            this.state.usr +
            "&password=" +
            this.state.pwd}`, {
            method: 'get',
            headers: {
                'Content-Type': 'application/json'
            }
        })
            .then(res => {
                console.log(res);
                //this.props.history.push("/dashboard");
                //console.log(window.location);
                window.location = window.location.origin+"/dashboard";
                //this.props.toggle();
                //this.props.updateUserIntoState(this.state.id);
            })
            .catch(err => console.log(err));
        //console.log(response);
    };`
