### ISSUE TITLE
Props not converted to camelCase by default

### ISSUE THREAD

**Issue by igorroch** [reactjs/React.NET#531]
According to [#330](https://github.com/reactjs/React.NET/issues/330) json should be converted by default.

But if we use this example
`@Html.React("ReactWorld", new { Name = "World" })`

it will be rendered as 
`ReactDOM.hydrate(React.createElement(ReactWorld, {"Name":"World"}),...`

Minimal [repo](https://github.com/igorroch/React.NET-issue-531) to reproduce.

**Comment by wub** [comment]
That's in .NET Core I believe.

**Comment by tachyon1337** [comment]
You need to set up the camelCase behavior in the startup file. Something like

```csharp
app.UseReact(config => {
        config
            .SetJsonSerializerSettings(new JsonSerializerSettings
            {
                StringEscapeHandling = StringEscapeHandling.EscapeHtml,
                ContractResolver = new CamelCasePropertyNamesContractResolver()
                      
            });
});
```

**Comment by dustinsoftware** [comment]
Looks like this is intentional - we won't be able to change this in the source code without breaking existing clients. 

https://github.com/reactjs/React.NET/blob/5f5f65d88c194d7c50e71ff8cb6d4a8e06b48aea/src/React.Core/ReactSiteConfiguration.cs#L43-L46

However, in ASP.NET core projects, that behavior is overridden:

https://github.com/reactjs/React.NET/blob/3c086e5454271d1030afa800df9dd123e2d300d6/src/React.AspNet.Middleware/ReactBuilderExtensions.cs#L52-L54.
