### ISSUE TITLE
Mobx state being kept between page loads

### ISSUE THREAD

**Issue by knyzorg** [reactjs/React.NET#573]
CSHTML: 

    <div>
        @Html.React("Components.Test", new { }, serverOnly: false)
    </div>

    <script src="@Url.Content("~/js/vendor.js")"></script>
    <script src="@Url.Content("~/js/app.js")"></script>

    @Html.ReactInitJavaScript()

Test Component:

```
@observer
export class Test extends React.Component<null> {
    constructor(props) {
        super(props)
        store.number++;
    }
    render() {
        return <p>{store.number}</p>
    }
}
```

MobX stuff:

```
class ChartDataStore {
    @observable number = 0;
}

const store = new ChartDataStore();
```

# Issue 

When the test component is rendered, I expect it to output the number 1 every time because on each page load, the mobx state should not be kept.

The actual result is after every few page loads the number increments. At first it is 1, then it is 2, then 3, and so on.

The issue is only present on server-side, client-side is not affected.

The issue is also present between different pages (i.e. two pages which render the Test component end up sharing the mobx state).

I speculate that whatever system is being used to render the React is using the same page for all components and never resets it.

**Comment by dustinsoftware** [comment]
Correct. You can disable the re-usable engine behavior though in your
startup config with .SetReuseJavascriptEngines(false).

The library assumes that components do not have side effects in either the
constructor or render, so that is why it re-uses the loaded JavaScript
between requests.

Dustin

**Comment by knyzorg** [comment]
Oh my, thank you so much. I struggled a lot with that. 

Should be added somewhere to this page: https://reactjs.net/guides/server-side-rendering.html

How much of a performance hit is to be expected?

**Comment by Daniel15** [comment]
I think you'd find the same thing with Node.js as well - The server-side reuses the JS engine rather than creating a new one each time, so any state that you set on the server-side is global for the app. There's a few approaches to reusing JS engines server-side and also having request-specific state, like generating an ID for the request and using that as the key in an object. Make sure you clean up any state after the request ends, to avoid the memory usage constantly rising.

> How much of a performance hit is to be expected?

I haven't measured it in a while, but it does mean that all the JS needs to be reloaded every time instead of having a warm JS engine ready to go, so it will affect performance a bit.
