### ISSUE TITLE
Using Cassette with AddPerSubDirectory in debug mode results in DirectoryNotFound exception

### ISSUE THREAD

**Issue by danrien** [reactjs/React.NET#58]
Environment (*emphasis mine*): Version Information: (*Mono*) 3.10.0 (tarball Wed Nov 5 12:50:04 UTC 2014); ASP.NET Version: 4.0.30319.17020 (*XSP*)

Steps to Reproduce:

1. Call `AddPerSubDirectory` on the directory containing the jsx files. In this specific case, it was just `Scripts`.
2. Set `debug="true"` in either the `<cassette />` tag or the `<compilation />` tag, i.e `<compilation defaultLanguage="C#" debug="true"> ... </compilation>`.
3. Reference the scripts folder(s) in the view and run the project
4. Upon inspection of the files that the browser tried to retrieve, a 500 error is returned for the JSX files, such as: `System.IO.DirectoryNotFoundException
Could not find a part of the path "/home/david/workspaces/perfect_cookie/project_perfect_cookie/project_perfect_cookie/cassette.axd/asset/Scripts/tutorial.jsx".`

Additional information:
* Standard JS files are returned fine, in their unminified form

**Comment by tulbox** [comment]
I also can confirm this, but in my case, it's for a scenario as per the following:

           var react = new[]
            {
                "~/content/js/react/react.js",
                "~/content/js/react/react-bootstrap.min.js",
                "~/content/js/react/shipping.react.jsx"
            };
            bundles.Add<ScriptBundle>("admin.js", react, x => x.PageLocation = "admin");

Ditto for using with a bundle.txt file:

`bundles.Add<ScriptBundle>("~/content/js/react", x => x.PageLocation = "admin");`

As @danrien states, this can be fixed by switching any .jsx files to a .js extension.

**Comment by calebroseland** [comment]
Not sure if it is technically correct, but I'll paste this here incase it helps anyone.

If you remove the *.jsx handler in web.config, it should fall back to using the cassette.axd handler. I commented out the following line and Cassette delivered in while in debug=true just fine.

.

**Comment by Daniel15** [comment]
Turns out this has to do with the order of the HTTP handlers in your Web.config file. When the JSX handler is listed first, it picks up the request even though it should actually go to Cassette. Ensure the Cassette handler is listed **before** the JSX handler in `system.webServer/handlers` and you should be fine.
