### ISSUE TITLE
Question: Calling C# methods from componentWillMount

### ISSUE THREAD

**Issue by prestond123** [reactjs/React.NET#594]
I've been using ReactJs.NET since mid 2016, and it is working perfectly, this is just a question.

We use isomorphic/server-side rendering, as per the documentation you have provided. However, I have seen many examples, in the NodeJs community, of components which use the componentWillMount method, to call business logic methods to initialise components.  

Our SPA allows for the user to have a dynamic set of panels loaded - each are unique components not specifically related to one another.  It would be useful, and maybe more intuitive, if the components could initialise themselves on the server, without having to pass the data down from: Html.React().  The problem is that the server is C# not JavaScript.  

Currently we either pass initial data (props) down through Html.React on the server, or do an AJAX call in the componentDidMount on the client.  

Any thoughts whether or how this could be achievable please?

Maybe being able to parse inline JSX, using an APS.NET/MVC @section (though this would not be ideal, especially if you use webpack etc..)?  

Thanks 
Dave

**Comment by Daniel15** [comment]
JavaScriptEngineSwitcher does support embedding C# objects and types, which might be useful in this case: https://github.com/Taritsyn/JavaScriptEngineSwitcher/blob/9547018d9086144fef96db4a76bb5f649f76476f/src/JavaScriptEngineSwitcher.Core/IJsEngine.cs#L156-L173. However, I don't think there's much documentation for it (cc @Taritsyn) and I've never tried it in conjunction with ReactJS.NET.

Some issues I can think of:
1. This functionality is not exposed through `ReactEnvironment`. If it was, you'd be able to  do something like `ReactEnvironment.Current.EmbedHostObject("Foo", SomeObject)`, or `ReactEnvironment.Current.Engine.EmbedHostObject` if we just decide to expose the entire Engine (https://github.com/reactjs/React.NET/blob/master/src/React.Core/ReactEnvironment.cs#L150-L153)
2. Since JS engines are pooled (via JSPool), I think we'd need to make sure to remove the object from the environment once the request completes, to avoid memory leaks. I'm not sure if `RemoveVariable` does that, or if it'd need to be a new method added to JavaScriptEngineSwitcher.

If you don't mind compiling your own version of ReactJS.NET, you may be able to play around with this and see if it works for your use case 👍

**Comment by Taritsyn** [comment]
> However, I don't think there's much documentation for it (cc @Taritsyn) and I've never tried it in conjunction with ReactJS.NET.

This functionality has not yet been documented. See a examples of using the `EmbedHostObject` and `EmbedHostType` methods in [unit tests](https://github.com/Taritsyn/JavaScriptEngineSwitcher/blob/956ebb157632aacfded24f1a0aa6bc49e86202a3/test/JavaScriptEngineSwitcher.Tests/InteropTestsBase.cs).

**Comment by dustinsoftware** [comment]
This would be very cool, let's keep this issue open for adding support.

**Comment by dustinsoftware** [comment]
I'm closing issues for future work like this that aren't actively being worked on, but would be open to adding support for this!

#655
