### ISSUE TITLE
Rendering without HTTPContext

### ISSUE THREAD

**Issue by RAAAJohnson** [reactjs/React.NET#600]
I'm able to generate the HTML from a react component with the following code when processing an Http request. However the initialization blows up when ran elsewhere. Is it possible to render a component to html without an HTTPContext?

`
var environment = ReactEnvironment.Current;
var reactComponent = environment.CreateComponent(component, props);
var html = reactComponent.RenderHtml(renderServerOnly: true);
`

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at React.AspNet.HttpContextLifetimeProvider.get_Registrations()
   at React.AspNet.HttpContextLifetimeProvider.GetObject()
   at React.TinyIoC.TinyIoCContainer.CustomObjectLifetimeFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) 
```

**Comment by Daniel15** [comment]
This is because some classes are registered "per request":
https://github.com/reactjs/React.NET/blob/5cbcd22e09444086401d51e65653505d49734146/src/React.AspNet.Middleware/ReactBuilderExtensions.cs#L65-L80

If there's no current request, this won't work.

One potential solution I can think of is to update `HttpContextLifetimeProvider` to handle the case when there's no current request, and just use transient instances (create a new instance on every call) in that case. We'd need to test and ensure there's no memory leaks though.

cc @dustinsoftware - What do you think of this?

**Comment by coka** [comment]
This is like #449, but for .NET Core, right? Maybe there is something similar to `HostingEnvironment` in the newer framework.

**Comment by RAAAJohnson** [comment]
Thanks for the explanation Daniel15. Right coka it does look similar and I am running on .NET Core.

**Comment by dustinsoftware** [comment]
> One potential solution I can think of is to update HttpContextLifetimeProvider to handle the case when there's no current request, and just use transient instances (create a new instance on every call) in that case. We'd need to test and ensure there's no memory leaks though.

I like this, let's keep this issue open until we add support for this.

**Comment by dustinsoftware** [comment]
I'm closing issues for future tasks like this that aren't actively being worked on, but would be open to adding support for this!

#655
