### ISSUE TITLE
Insert localization string on the fly

### ISSUE THREAD

**Issue by slav** [reactjs/React.NET#62]
.NET has quite powerful support for string localization via resources and automatic string insertion depending on the currently selected localization resource.

I'm wondering if it's possible to take advantage of this mechanism in reactjs.net to make text in components localizable and easy to translate?

**Comment by Daniel15** [comment]
An interesting question. None of the projects I've worked on at the past have used .NET string localization (nor did my previous employer).  Can you show an example of how you'd use it today?

**Comment by Daniel15** [comment]
I'm going to close this since I didn't hear back and haven't had any other requests for this, but please feel free to reopen it with more information. Thanks!

**Comment by Hekku2** [comment]
I also ran into this issue while investigating if I can use this with current project.

Currently one way to use localizations strings is to render partial .cshtml-file which has script section where translations are used.

I think this way is ugly and it would be very laborious to use for every text element in page. And if someone knows better way, please tell me.

This example is from knockout validation localizations 
```
<script type="text/javascript">
    if (ko && ko.validation) {
            ko.validation.rules.required.message = "@Html.Raw(Translations.Validation_Required)";
            ko.validation.rules.maxLength.message = "@Html.Raw(Translations.Validation_MaxLength)";
            ko.validation.rules.digit.message = "@Html.Raw(Translations.Validation_Digit)";
    }
</script>
```

Best way I can come up with is to use translations straight from the jsx-file, which would be ran trough Razor(?) or some kind of "replace X from resource file" before compiling/bundling the jsx-file to js-file.

```
var WarningComponent= React.createClass({
    render: function() {
        return (
          <div className="alert alert-warning">
            @Translations.Warnings_MissingInformation
          </div>
      );
    }
});
```

**Comment by PeteDuncanson** [comment]
Couple of options, if you don't have too many messages/languages then you could render them all out in a JSON object and just include that in your bundle? Let the JS handle which translation to show rather than the Razor.

If you have too many languages/settings and don't want to include them all for all users you can have "global" objects which you can get your bundle to assume exist without you having to include them in your bundle (ie you are going to included them in another script tag somewhere). If you go that route then you can use your Razor to work out which js file of settings to use and just included the right one for the current language. For bonus points this file could be rendered itself via Razor if the settings need to come from a CMS or similar.
