### ISSUE TITLE
Error Boundary

### ISSUE THREAD

**Issue by jerrywithaz** [reactjs/React.NET#740]
Hi! Quick question,

How do you use the error boundary param? I can't find any documentation on it so I'm a little confused.

I have Components that are wrapped in an Error Boundary Component if an error is thrown, it works great on the client but not on the server. How would I go about displaying the Error Boundary Component if an Error occurs on the server?

For example, if I have the following: 
```
@Html.React("Page", new {
    version = Model.Version,
})
```
And one of the components nested in the component tree gets an error I would like for that Component to render the Error Boundary rather than crash the whole page. Is that possible?

Thanks!

**Comment by dustinsoftware** [comment]
Hi @jerrywithaz. [SetExceptionHandler](https://github.com/reactjs/React.NET/blob/b3faf179c2d06408d06fdf5e31ebe76434cb47b0/src/React.Core/ReactSiteConfiguration.cs#L324) is what you're looking for. This provides a mechanism for your app to log an error instead of it silently ignoring it. Hope that helps! Feel free to comment if that doesn't work.
