### ISSUE TITLE
Invalid checksum with server-side rendering

### ISSUE THREAD

**Issue by moranms** [reactjs/React.NET#79]
Hi, I've implemented server-side rendering for my react components, following the tutorial. I am also using the SignalR library to perform frequent client-side updates to the React components states.

I'm seeing the following error when my page initially loads: 

>React attempted to use reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server.

It appears the issue is a result of using javascript functions to format my data model in the render method. So for example, I have:
```
render: function(){
return (
<em>{self.FormatTimeElapsed(this.props.data.Time)}</em>
);
}
```
where FormatTimeElapsed simply converts the provided DateTime to a more readable format. Because of this formatting, when calling `@Html.ReactWithInit("MyComponent", new {initialData = model})`, the HTML produced does not reflect the javascript formatted values. So I end up with static markup in my page that does not match what React expects, since the JS formatting methods were never called for the static portion. The result is static `<em data-reactid=".usjgfr2yys.1.0.$1.0.3.0">12:NaN PM</em>` where it should be `<em data-reactid=".usjgfr2yys.1.0.$1.0.3.0">2 hours ago</em>`

Is my only option here to modify my model, implementing the same formatting methods server-side? I'd rather NOT have to massage the model data here, but I guess I'm not sure if there's any other option.

**Comment by PeteDuncanson** [comment]
When you get this its not the end of the world, it just means React has to re-draw everything again client side. Always nice to get rid of it though if possible so lets do some digging.

One issue you might have is the time that it should be comparing the date from, this could be greatly different depending on the clients time on their device compared to the time on the server (or timezone). If your site is targeted to a single country (with a single timespan) like here in the UK then we've got around that by sending down the server time and using that for the comparison to rule out any time differences on the users machine. However if in the states this might not work.

A possible fix is to NOT render the element out on the server OR client and then setup a setTimeout in the componentDidMount method to get it to redraw via a state change thats run in the setTimeout callback? The server won't run the callback but the client will but the initial HTML both generate will match and the error should go away.

**Comment by Daniel15** [comment]
> It appears the issue is a result of using javascript functions to format my data model in the render method. 

The error actually means that the `render` method returned something different when called server-side than when it was called client-side. These should be returning the same thing. This points to an issue in the JavaScript. Try turning off JavaScript in your browser and loading the page (so it's only rendered server-side). Then in a separate tab, turn on JavaScript and load the page. Put the two side by side and look for any obvious differences. You can also diff the generated DOM (HTML in 'View Source' vs HTML in 'Inspect Element' -> right-click -> copy as HTML) to find changes.

A very basic approach to debugging is to remove everything from your render method and see if the error disappears. If it does, keep adding stuff back piece by piece until you find the part that causes the error.

> Is my only option here to modify my model, implementing the same formatting methods server-side

Nope, the whole point of server-side rendering is to use the JavaScript rendering methods server-side too, so there's only one implementation. The issue here is that there's something wrong in the implementation such that it's doing something different server-side compared to client-side.

I'm going to "close" this issue since it's not a bug in ReactJS.NET, but please feel free to continue using the issue for discussion. Thanks!

**Comment by Jecoms** [comment]
I ran into this when one of my components was a clock and I set the initial state to the current time. This will of course be different than my client-side render, so it gave me this warning. 

My solution was to set the initial state for the time/date to an empty string and set the time to new Date() in componentDidMount(). The initial renders now match as I only display the time if the state variable is truthy.

As far as a state variable that is dependant on run-time, would this be the recommended "Thinking in React" way of handling this situation?
