### ISSUE TITLE
Import third party modules without Webpack soon ?

### ISSUE THREAD

**Issue by oudoulj** [reactjs/React.NET#804]
Hi,
I know you currently have to **use Webpack to import third party modules** but I was wondering if there was any plan to add this long-awaited capability in the near future ?
Dustin said earlier this year that :

> ES6 modules are not **yet** natively supported without webpack

https://github.com/reactjs/React.NET/issues/716
Please notice the "yet" ;-)
Thank you.

**Comment by dustinsoftware** [comment]
Hah yeah, still thinking this one through. The trick is to figure out the best way to do this on server render. We could run JSX Babel transforms the code pretty easily and leave the import statements alone (maybe this already works?) but this would break browsers that do not natively support ES modules, plus we would have to build a shim around BrowserFS roe somehow roll our own ES module resolver (complex!). 

A simpler solution will probably just run webpack for you instead of requiring that you pass in the path to a built bundle and internalizing the webpack config, which is how many CLI tools work already (such as Create React App). I want to get lazy loading working anyway so that apps can use code splitting, there’s a WIP branch on this repo that explores some of how that will work. Not a blocker though to having first class webpack support.

**Comment by dustinsoftware** [comment]
Initial investigation complete - somehow doing module resolution on the fly is going to be a very complex undertaking, so I can't say when we will be able to support this. It is more likely that we will make using this library with `create-react-app` easier and recommend that for works-out-of-the-box scenarios. (e.g. #816)
