### ISSUE TITLE
V8 compile scripts if reused?

### ISSUE THREAD

**Issue by PeteDuncanson** [reactjs/React.NET#85]
Not sure if this is a JSPool thing or a React.net thing but been reading about compiled scripts. From my understanding these are the parsed version of a script, that parsing takes time so by caching the resultant "byte code" and passing that into the ClearScript engine you can save on that parsing time. As the user scripts are re-used over and over it might be worth looking into saving these down as compiled scripts and then using them when initialising the engines?

Again might be more performances savings here due to them being re-used over and over.

Side note, this a great code base, real easy to poke around and the fact we are raising this minor tuning tweaks is only a good thing. Great work @Daniel15

**Comment by Daniel15** [comment]
At the moment, I think it would have to be added to [JavaScriptEngineSwitcher](https://github.com/Taritsyn/JavaScriptEngineSwitcher) first, as that's the abstraction layer I'm using for JavaScript engines. Perhaps I should switch to using V8 directly rather than JavaScriptEngineSwitcher? I'm using two different V8 integration libraries (ClearScript on Windows and a fork of VroomJs on Linux and Mac OS) so I'd still need an abstraction layer of some sort.

> Side note, this a great code base, real easy to poke around and the fact we are raising this minor tuning tweaks is only a good thing. Great work @Daniel15

Thanks! :D

**Comment by Daniel15** [comment]
I think the pooling provided by JSPool should be sufficient for now. If we wanted to implement better V8 compilation then either that should be added to JavaScriptEngineSwitcher or we should switch to using ClearScript (for Windows) + VroomJs (for Mac OS and Linux) directly. I like the abstraction layer JavaScriptEngineSwitcher provides, but it makes it more difficult to do anything engine-specific.

**Comment by PeteDuncanson** [comment]
I found the additional repo for JavascriptEngineSwitcher needed to do our debugging and optimising a bit of a chore plus the chances of getting PR accepted get stretched as our stuff is pretty specific to V8. As the code is only parsed once then left in the pool the gains of compiling would be minimal I suppose.
