### ISSUE TITLE
[Question] How to perform performance profiling?

### ISSUE THREAD

**Issue by mitikov** [reactjs/React.NET#889]
Hi folks,
We have profiled our page load time and a vast majority is spent on server-side (loading scripts into the react environment).

The questions are:
1) How to properly do performance analysis for React.NET on a server-side?
2) How to understand/measure the wallclock time distribution on script load?
3) Are there any guides/blogs/tricks on how to improve the React.NET performance?

Although I can provide a few PerfView flame graphs showing slow place specifically in our solution, I would ask you to treat this question as a general one.

Thank you.

**Comment by mitikov** [comment]
The `bundle.js` used is around 2.5 MB (after minification) - loading it on each page request is killing us.

Making use of `Precompilation` API driven by IJS engine - brings 50% page load time win (1178 vs ~570 ms).

While that is still not enough :(

**Comment by dustinsoftware** [comment]
The code splitting story could be better - right now you need to use webpack and have separate, dedicated bundles for your features, and do a hard-reload when transitioning between them. If you don't need server-side rendering for some large components, use lazy loading with webpack and call `import('./some-component')` in `useEffect` or `componentDidMount`.

It would be good to have some documentation on this because this is pretty common as apps grow in size, so I'll leave this issue open.

**Comment by dustinsoftware** [comment]
To answer your question more directly:

1. Use a tool like MiniProfiler.Step around `@Html.React` by using a custom Html Helper Extension to wrap the call.
2. Use tools like webpagetest to understand the download and parse time for remote browsers. If profiling locally, Chrome and Firefox both have excellent tools that show you the wall clock time for each step.
3. The main recommendation is to use engine pooling and keep an eye out for libraries that are making your app bundle large. The [.NET Core sample](https://github.com/reactjs/React.NET/blob/b48be73bf8ee5bcdc028a810587ad7c538993202/src/React.Sample.Webpack.CoreMvc/webpack.config.js) has a webpack config that splits the vendor bundle out, but does not demonstrate separate app bundles.
