### ISSUE TITLE
Using RMWC and React.NET

### ISSUE THREAD

**Issue by MightyDesertFox** [reactjs/React.NET#898]
Hello!

I'm trying to use RMWC, a React wrapper for Material Design (Web) Components in my MVC.net application.

I'm successful using ReactJS.NET, but when I try to use the RMWC components I keep getting errors (probably due to my limited experience with it) that I cannot solve.

In my Ideas.jsx, I want to do this:
```
import Button from '@rmwc/button';

ReactDOM.render(
    <Button>Hello World</Button>,
    document.getElementById('content'),
);
```

Which is pretty simple code.

In my view, I have the following:
`<script src="@Url.Content("~/js/Views/Ideas.jsx")"></script>`

And when running it, I get the following error:
`Uncaught SyntaxError: Unexpected identifier` happening in the first line, where the "import" is

Thoughts? Thanks!

**Comment by dustinsoftware** [comment]
Does it work with the webpack docs?

**Comment by MightyDesertFox** [comment]
Hi!

Well, unfortunately the code for webpack (both in the docs and in the repo) don't work :(

VS cannot even load the repo's Project...

Any ideas on how to proceed?

**Comment by joshmccall221** [comment]
Without the webpack middleware it will throw error because the browser does not understand import / modules. 

You need to either use the webpack middleware (which does bundling /transpiring for you) or reference the js (not jsx) after its been transformed. 

Another option is to use Babel’s standalone cdn script to run jsx on the fly. 

Is this a core or .net framework app?
