### ISSUE TITLE
Could we use React Routing mechanism both server and client side?

### ISSUE THREAD

**Issue by glikoz** [reactjs/React.NET#98]
Could you give sample for it? Is it possible?

**Comment by Daniel15** [comment]
I think @PeteDuncanson was attempting to use React Router from ReactJS.NET, although I'm not sure how far he got with it.  I don't know how difficult it would be to do.

**Comment by PeteDuncanson** [comment]
It's doable but we needed to write a new method to do it as router needs to be passed the URL.

Our fork has the mods in if you want to take a look.

@daniel15 been playing with ideas for making the js code a bit more flexible. Latest idea is to pass in some variables to the engine for URL (and anything else that might be handy) then have a file with the js to run react rather than having it hard coded in the c#. File watcher on the file to pick up changes of course. Could make the whole setup more flexible?

Sent from my iPhone

On 7 Mar 2015, at 01:36, Daniel Lo Nigro <notifications@github.com<mailto:notifications@github.com>> wrote:


I think @PeteDuncanson<https://github.com/PeteDuncanson> was attempting to use React Router from ReactJS.NET<http://ReactJS.NET>, although I'm not sure how far he got with it. I don't know how difficult it would be to do.

**Comment by dgwaldo** [comment]
Now looking into using React Router from ReactJS.NET as well.  Pulled Pete's branch and tried dev-build, looks like the build is failing..  Will try to work around that.   Would love to see this as a feature in the mainline.

**Comment by PeteDuncanson** [comment]
Back from holiday so just catching up. How did you get on?

**Comment by dgwaldo** [comment]
Haven't dedicated to much time, as the build is failing, and couldn't get it building.

**Comment by Daniel15** [comment]
Closing this in favour of #64

**Comment by PeteDuncanson** [comment]
@dgwaldo trying our fork and it compiled just fine, did you run the dev.build file first as per the original ReactJS.net docs? That would cause an error but it does it for the original too. Fingers crossed thats the issue, if not let me know as can't recreate here.

**Comment by dgwaldo** [comment]
@PeteDuncanson   The teamcity build was failing, looks like its good to go now.  However, my coworker has been using Node to serve the React prototype, seems to be working great so far.
